# Generated by Django 4.1.2 on 2022-11-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todooapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-11-12'),
            preserve_default=False,
        ),
    ]
